### ISSUE TITLE
The "@import url" link is broken.

### ISSUE THREAD

**Issue by Zutyosh** [CelestialReaver/Synthwave84-Powercord#1]
I am writing to you to point out that you have not updated the link to the source.css file.

Because when we go to the address : https://celestialreaver.github.io/Synthwave84/css/source.css

We get a nice 404 page.
This causes the theme to crash and not load.
![image](https://user-images.githubusercontent.com/69845574/180623439-07961ddf-2610-4f5a-8928-8c7f4bd49b99.png)

**Comment by CelestialReaver** [comment]
that is a bummer! i was rearranging my repos and missed that. thanks for letting me know. should be resolved.

** also - thanks for letting me know. i hadn't seen anything in the powercord discord server.
